Task/Models/DossierStructure.cs
using System;
using System.Collections.Generic;

namespace Task1.Models;

public partial class DossierStructure
{
    public int Id { get; set; }

    public int? ParentId { get; set; }

    public int? OrderNumber { get; set; }

    public string? SectionCode { get; set; }

    public string? Name { get; set; }

    public virtual ICollection<DossierStructure> InverseParent { get; set; } = new List<DossierStructure>();

    public virtual DossierStructure? Parent { get; set; }
}

Task/Controllers/DossierStructuresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Task1.Models;

namespace Task1.Controllers
{
    public class DossierStructuresController : Controller
    {
        private readonly TaskContext _context;

        public DossierStructuresController(TaskContext context)
        {
            _context = context;
        }

        // GET: DossierStructures
        public async Task<IActionResult> Index()
        {
            List<TreeViewNode> nodes = new List<TreeViewNode>();

            foreach (var type in _context.DossierStructures.Include(d => d.Parent))
            {
                nodes.Add(new TreeViewNode { id = type.Id.ToString(), parent = type.ParentId.ToString() != "" ? type.ParentId.ToString() : "#", text = type.SectionCode + " " + type.Name, orderNumber = type.OrderNumber.ToString() });
            }
            if (nodes.Count == 0)
            {
                nodes.Add(new TreeViewNode { id = "1", parent = "#", text = "1.1 Административная информация", orderNumber = "0" });
                nodes.Add(new TreeViewNode { id = "2", parent = "1", text = "1.2 Общая информация", orderNumber = "1" });
            }
            //Serialize to JSON string.
            ViewBag.Json = JsonConvert.SerializeObject(nodes);
            return View();

        }
        [HttpPost]
        public IActionResult Index(string selectedItems)
        {
            // Проверяем, что строка не пустая
            if (selectedItems.Length == 0)
            {
                return RedirectToAction("Index");
            }

            // Удаляем все записи из таблицы Users
            _context.DossierStructures.RemoveRange(_context.DossierStructures);
            _context.SaveChanges();

            // Преобразуем строку в список объектов TreeViewNode
            List<TreeViewNode> items = JsonConvert.DeserializeObject<List<TreeViewNode>>(selectedItems);

            // Создаем переменные для хранения данных
            DossierStructure doss = new DossierStructure();
            int OrderNumber = 0;
            Dictionary<string, int> idParentId = new Dictionary<string, int>(); // Словарь для хранения id и parentid элементов

            // Перебираем все элементы в списке
            foreach (var a in items)
            {
                // Если элемент является корневым
                if (a.parent == "#")
                {
                    // Создаем новый объект DossierStructure с данными из элемента
                    doss = new DossierStructure()
                    {
                        Name = TextRegexS(a.text),
                        SectionCode = NumberRegexS(a.text),
                        OrderNumber = 0
                    };
                    // Сбрасываем счетчик порядкового номера
                    OrderNumber = 0;
                }
                // Если элемент является дочерним
                else
                {
                    // Увеличиваем счетчик порядкового номера
                    OrderNumber++;
                    // Создаем новый объект DossierStructure с данными из элемента и parentid из словаря
                    doss = new DossierStructure()
                    {
                        Name = TextRegexS(a.text),
                        ParentId =  idParentId[a.parent],
                        SectionCode = NumberRegexS(a.text),
                        OrderNumber = OrderNumber
                    };
                }

                // Добавляем объект в контекст базы данных
                _context.DossierStructures.Add(doss);
                // Сохраняем изменения в базе данных
                _context.SaveChanges();
                // Добавляем пару ключ-значение в словарь, если ключ не существует
                idParentId.TryAdd(a.id, doss.Id);
                // Если элемент является корневым, запоминаем его id
            }
            // Возвращаемся на главную страницу
            return RedirectToAction("Index");
        }

        public string NumberRegexS(string s)
        {
            string pattern = @"\d+(\.\d+)*";

            // Создать объект Regex с этим шаблоном
            Regex regex = new Regex(pattern);

            // Найти первое совпадение в строке
            Match match = regex.Match(s);
            return match.Value;
        }
        public string TextRegexS(string s)
        {
            string pattern = @"\d+([\.,]\d+)*";

            // Создать объект Regex с этим шаблоном
            Regex regex = new Regex(pattern);

            // Заменить все совпадения на пустую строку
            string result = regex.Replace(s, "");
            return result;
        }

    }
}

Task/Views/DossierStructures/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./../../dist/themes/default/style.min.css" />
</head>
<body>
    <div id="kt_docs_jstree_contextual" style=" max-height: 50vh; overflow-y: auto; " class="demo"></div>
    <div id="info"></div>
    <form method="post" asp-controller="DossierStructures" asp-action="Index">
        <input hidden name="selectedItems" id="selectedItems" />
        <input type="submit" value="Сохранить" />
    </form>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
    <script>
  // Обработчик события выбора узла в дереве
  $('#kt_docs_jstree_contextual').on('select_node.jstree', function (e, data) {
    var node = data.node; // Получить выбранный узел
    var text = node.text; // Получить текст узла
    var number = text.match(/\d+(\.\d+)*/)[0]; // Извлечь число из текста с помощью регулярного выражения, включая точки
    var textWithoutNumber = text.replace(/\d+(\.\d+)*\s*/, ''); // Удалить число из текста
    var info = document.getElementById('info'); // Получить элемент с id info
    info.innerHTML = '<p>SectionId: ' + number + '</p><p>Текст: ' + textWithoutNumber + '</p>'; // Вставить данные в элемент
    info.style.display = 'block'; // Показать элемент
  });
        $('#kt_docs_jstree_contextual').on('move_node.jstree', function (e, data) {
            var tree = $("#kt_docs_jstree_contextual").jstree(); // Получить объект дерева
            var nodes = tree.get_json(null, { flat: true }); // Получить все узлы в виде JSON-объекта
            var selectedItems = []; // Создать пустой массив для выбранных элементов
            $.each(nodes, function (i, node) { // Перебрать все узлы
                selectedItems.push({ // Добавить объект с данными узла в массив
                    text: node.text,
                    id: node.id,
                    orderNumber: node.li_attr.id,
                    parent: node.parent
                });
            });
            // Сериализовать массив в JSON-строку и сохранить в скрытом поле
            $('#selectedItems').val(JSON.stringify(selectedItems));
        })
  // Обработчик события изменения дерева
  $('#kt_docs_jstree_contextual').on('changed.jstree', function (e, data) {
    var tree = $("#kt_docs_jstree_contextual").jstree(); // Получить объект дерева
    var nodes = tree.get_json(null, { flat: true }); // Получить все узлы в виде JSON-объекта
    var selectedItems = []; // Создать пустой массив для выбранных элементов
    $.each(nodes, function (i, node) { // Перебрать все узлы
      selectedItems.push({ // Добавить объект с данными узла в массив
        text: node.text,
        id: node.id,
        orderNumber: node.li_attr.id,
        parent: node.parent
      });
    });
    // Сериализовать массив в JSON-строку и сохранить в скрытом поле
    $('#selectedItems').val(JSON.stringify(selectedItems));
  })
    .jstree({ // Инициализировать дерево с настройками
      "core": {
        "strings": { "lang": "ru" },
        "themes": {
          "responsive": false
        },
        "check_callback": true,
        "data": @Html.Raw(ViewBag.Json)
      },
      "types": {
        "default": {
          "icon": "ki-solid ki-folder text-primary"
        },
        "file": {
          "icon": "ki-solid ki-file  text-primary"
        }
      },
      "state": { "key": "demo2" },
      "plugins": ["dnd", "contextmenu", "state", "types"],
      "contextmenu": {
        "items": function ($node) {
          var tree = $("#kt_docs_jstree_contextual").jstree(true); // Получить объект дерева
          return {
            "create_child": { // Элемент меню для создания дочернего узла
              "separator_before": false,
              "separator_after": false,
              "label": "Добавить подчиненный узел",
              "action": function (obj) {
                $node = tree.create_node($node); // Создать дочерний узел
                  tree.edit($node); // Редактировать узел
              }
            },
            "create_after": { // Элемент меню для создания узла после текущего
              "separator_before": false,
              "separator_after": false,
              "label": "Добавить строку после",
              "action": function (obj) {
                $node = tree.create_node($node.parent, {}, "after", $node); // Создать узел после текущего
                  tree.edit($node); // Редактировать узел
              }
            },
            "create_before": { // Элемент меню для создания узла перед текущим
              "separator_before": false,
              "separator_after": false,
              "label": "Добавить строку перед",
              "action": function (obj) {
                $node = tree.create_node($node.parent, {}, "before", $node); // Создать узел перед текущим
                  tree.edit($node); // Редактировать узел
              }
            },
            "delete": { // Элемент меню для удаления узла
              "separator_before": false,
              "separator_after": false,
              "label": "Удалить узел",
              "action": function (obj) {
                  tree.delete_node($node); // Удалить узел
              }
            }, "edit": { // Элемент меню для редактирования узла
              "separator_before": false,
              "separator_after": false,
              "label": "Редактировать узел",
              "action": function (obj) {
                  tree.edit($node); // Редактировать узел
                }

            }
          };
        }
      }
    });
    </script>
</body>
</html>